source 'https://github.com/CocoaPods/Specs.git'

platform :tvos, '9.0'
link_with 'OwnTracksCTRLTV'
xcodeproj 'OwnTracksCTRLTV.xcodeproj'

#pod 'CocoaLumberjack'
pod 'MQTTClient'
#pod 'Fabric'
#pod 'Crashlytics'


