all: Connection-22.png \
	Info-22.png \
	Kiosk-22.png \
	Logout-22.png \
	Map-22.png \
	Track-22.png \
	Vehicles-22.png \
	Zoom-22.png 

clean:
	rm Connection*png
	rm Info*png
	rm Kiosk*png
	rm Logout*png
	rm Map*png
	rm Track*png
	rm Vehicles*png
	rm Zoom*png

Connection-22.png:Connection.svg
	./size22.sh Connection.svg

Info-22.png:Info.svg
	./size22.sh Info.svg

Kiosk-22.png:Kiosk.svg
	./size22.sh Kiosk.svg

Logout-22.png:Logout.svg
	./size22.sh Logout.svg

Map-22.png:Map.svg
	./size22.sh Map.svg

Track-22.png:Track.svg
	./size22.sh Track.svg

Vehicles-22.png:Vehicles.svg
	./size22.sh Vehicles.svg

Zoom-22.png:Zoom.svg
	./size22.sh Zoom.svg

